### PR TITLE
Add dark mode option.

### PR DESCRIPTION
**Pull request by ancamaria99**
Screenshot 2020-09-11 at 4 39 39 PM - Display 1

### CODE REVIEW

**Review by stofee — COMMENTED** [review]
can we mowe the time selection stuff up to the header too? now they waste 2 lines instead of sharing one... rest LGTM

**Comment by andrey-star** [comment]
> can we mowe the time selection stuff up to the header too? now they waste 2 lines instead of sharing one... rest LGTM

for the changes to be applied we will need to create a new parent comp for header and EnvsComp
it'll take some time, lets add a TODO

**Comment by ancamaria99** [comment]
> > can we mowe the time selection stuff up to the header too? now they waste 2 lines instead of sharing one... rest LGTM
> 
> for the changes to be applied from sibling we will need to create a new parent comp for header and EnvsComp
> it'll take some time, lets add a TODO

ok, @stofee can you approve this so we can merge?

**Comment by ancamaria99** [comment]
> > > can we mowe the time selection stuff up to the header too? now they waste 2 lines instead of sharing one... rest LGTM
> > 
> > 
> > for the changes to be applied from sibling we will need to create a new parent comp for header and EnvsComp
> > it'll take some time, lets add a TODO
> 
> ok, @stofee can you approve this so we can merge?

Created issue and added TODO.

**Review by stofee — APPROVED** [review]

**Pull request merged**
