### PR TITLE
Create script that generates pb file.

### PR DESCRIPTION
**Pull request by ancamaria99**

### CODE REVIEW

**Comment by stofee** [comment]
pls fix the failing checks ;)

**Comment by ancamaria99** [comment]
> pls fix the failing checks ;)

yes, I am doing that now, it's a draft pr

**Comment by stofee** [comment]
> pls fix the failing checks ;)
namely:
https://github.com/googleinterns/step251-2020/pull/226/checks?check_run_id=1052068251 protoc not found

**Comment by stofee** [comment]
> > pls fix the failing checks ;)
> 
> yes, I am doing that now, it's a draft pr

oh ok, in this case pls do not send the pr until it is ready or start description as DO NOT SUBMIT in order to not to waste time for reviewers ;)

**Comment by ancamaria99** [comment]
> > > pls fix the failing checks ;)
> > 
> > 
> > yes, I am doing that now, it's a draft pr
> 
> oh ok, in this case pls do not send the pr until it is ready or start description as DO NOT SUBMIT in order to not to waste time for reviewers ;)

I thought since it's a label as 'draft' on github it would be ok.

**Review by stofee — APPROVED** [review]

**Pull request merged**
